var meuArray = [10, 14, 20, 9, 16, 22];
console.log(meuArray);
console.log(meuArray[0]);
console.log(meuArray[1]);
console.log(meuArray[2]);
console.log(meuArray[3]);
console.log(meuArray[4]);
console.log(meuArray[5]);
console.log(meuArray[0] + meuArray[0]);
console.log(meuArray[0] + meuArray[1]);
console.log(meuArray[0] + meuArray[2]);
console.log(meuArray[0] + meuArray[3]);
console.log(meuArray[0] + meuArray[4]);
console.log(meuArray[0] + meuArray[5]);
console.log(meuArray[1] + meuArray[0]);
console.log(meuArray[1] + meuArray[1]);
console.log(meuArray[1] + meuArray[2]);
console.log(meuArray[1] + meuArray[3]);
console.log(meuArray[1] + meuArray[4]);
console.log(meuArray[1] + meuArray[5]);
console.log(meuArray[2] + meuArray[0]);
console.log(meuArray[2] + meuArray[1]);
console.log(meuArray[2] + meuArray[2]);
console.log(meuArray[2] + meuArray[3]);
console.log(meuArray[2] + meuArray[4]);
console.log(meuArray[2] + meuArray[5]);
console.log(meuArray[3] + meuArray[0]);
console.log(meuArray[3] + meuArray[1]);
console.log(meuArray[3] + meuArray[2]);
console.log(meuArray[3] + meuArray[3]);
console.log(meuArray[3] + meuArray[4]);
console.log(meuArray[3] + meuArray[5]);
console.log(meuArray[4] + meuArray[0]);
console.log(meuArray[4] + meuArray[1]);
console.log(meuArray[4] + meuArray[2]);
console.log(meuArray[4] + meuArray[3]);
console.log(meuArray[4] + meuArray[4]);
console.log(meuArray[4] + meuArray[5]);
console.log(meuArray[5] + meuArray[0]);
console.log(meuArray[5] + meuArray[1]);
console.log(meuArray[5] + meuArray[2]);
console.log(meuArray[5] + meuArray[3]);
console.log(meuArray[5] + meuArray[4]);
console.log(meuArray[5] + meuArray[5]);